export const ADD_ROW = 'ADD_ROW';
export const ADD_COMPOSITE_ROW = 'ADD_COMPOSITE_ROW';
export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_COLUMNS = 'ADD_COLUMNS';
export const ADD_CONTAINER_ROW = 'ADD_CONTAINER_ROW';
export const ENCAPSULATE_CONTENT = 'ENCAPSULATE_CONTENT';
export const MOVE_CONTENT = 'MOVE_CONTENT';

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const CREATE_BLOCK = "CREATE_BLOCK";
export const CREATE_BLOCK_FIELD = "CREATE_BLOCK_FIELD";
export const ATTACH_BLOCK = "ATTACH_BLOCK";
export const GENERATE_PREVIEW = 'GENERATE_PREVIEW';


export const ADD_CONTENT_CHOOSE_TEMPLATE = "ADD_CONTENT_CHOOSE_TEMPLATE";
